name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Optional: Build and push Docker images (if using GitHub Container Registry)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images
        run: |
          docker compose build

      - name: Push Docker images
        run: |
          docker compose push || echo "Skipping push (no registry configured)"

      # SSH into EC2 and deploy using docker-compose
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /home/ubuntu/my-dashboard || (git clone https://github.com/wkdalsgh192/my-dashboard.git && cd my-dashboard)
            git pull origin master
            docker compose pull || true
            docker compose build --no-cache
            docker compose up -d
            docker image prune -f
